import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "/dashboard/main",
    title: "Dashboard",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
  {
    path: "/profile/mydetails",
    title: "Profile",
    iconType: "material-icons-two-tone",
    icon: "account_circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
  // {
  //   path: "/profile/mycontacts",
  //   title: "Contacts",
  //   iconType: "material-icons-two-tone",
  //   icon: "account_circle",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "badge bg-blue sidebar-badge float-right",
  //   submenu: [],
  // },
  {
    path: "/profile/mypermissions",
    title: "Permissions",
    iconType: "material-icons-two-tone",
    icon: "check_circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
  {
    path: "/dependant/dependants",
    title: "Dependants",
    iconType: "material-icons-two-tone",
    icon: "supervisor_account",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
  {
    path: "/organization/organizations",
    title: "Organizations",
    iconType: "material-icons-two-tone",
    icon: "business",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
  {
    path: "/warrant/warrants",
    title: "Warrants",
    iconType: "material-icons-two-tone",
    icon: "credit_card",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "badge bg-blue sidebar-badge float-right",
    submenu: [],
  },
];
